# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 21:39
from __future__ import unicode_literals

import djanalytics.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.CharField(default=djanalytics.models.generate_uuid, max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField(blank=True)),
                ('user_agent_md5', models.CharField(db_index=True, max_length=32, unique=True)),
                ('os', models.CharField(db_index=True, max_length=100)),
                ('os_version', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('browser', models.CharField(db_index=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('device', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('screen_width', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('screen_height', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9_]+$', 32), "Enter a valid 'type' consisting of letters, numbers, and/or underscores.", 'invalid')])),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern', models.CharField(blank=True, help_text='Deprecated, use an entry with name per domain instead', max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanalytics.Client')),
            ],
        ),
        migrations.CreateModel(
            name='IPFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netmask', models.CharField(max_length=19)),
                ('include', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanalytics.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(blank=True, max_length=25, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanalytics.Client')),
            ],
        ),
        migrations.CreateModel(
            name='PagePattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9_]+$', 32), "Enter a valid 'type' consisting of letters, numbers, and/or underscores.", 'invalid')])),
                ('name', models.CharField(max_length=80)),
                ('pattern', models.CharField(max_length=200)),
                ('display_path', models.CharField(help_text='How to display on reports', max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanalytics.Client')),
            ],
        ),
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9_]+$', 32), "Enter a valid 'type' consisting of letters, numbers, and/or underscores.", 'invalid')])),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration', models.DecimalField(decimal_places=0, max_digits=7, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanalytics.Page')),
            ],
            options={
                'get_latest_by': 'request_event__created',
            },
        ),
        migrations.CreateModel(
            name='PathFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_pattern', models.CharField(max_length=200)),
                ('include', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanalytics.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ReferrerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9_]+$', 32), "Enter a valid 'type' consisting of letters, numbers, and/or underscores.", 'invalid')])),
                ('name', models.CharField(max_length=80, unique=True)),
                ('pattern', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('tracking_key', models.CharField(db_index=True, default=djanalytics.models.generate_uuid, max_length=36)),
                ('tracking_user_id', models.CharField(db_index=True, default=djanalytics.models.generate_uuid, max_length=36)),
                ('protocol', models.CharField(max_length=10)),
                ('domain', models.CharField(db_index=True, max_length=100)),
                ('path', models.URLField(blank=True, db_index=True)),
                ('query_string', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('referrer', models.URLField(blank=True, max_length=2083, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('response_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('screen_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('screen_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanalytics.Client')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djanalytics.Location')),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36)),
                ('visit_date', models.DateField(db_index=True)),
                ('duration', models.DecimalField(decimal_places=0, max_digits=7, null=True)),
                ('conversion_count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanalytics.Device')),
                ('first_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_visit', to='djanalytics.Page')),
                ('last_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_visit', to='djanalytics.Page')),
                ('pages', models.ManyToManyField(through='djanalytics.PageVisit', to='djanalytics.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36)),
                ('clients', models.ManyToManyField(to='djanalytics.Client')),
            ],
        ),
        migrations.CreateModel(
            name='WebProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Web properties',
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanalytics.Visitor'),
        ),
        migrations.AddField(
            model_name='visit',
            name='web_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanalytics.WebProperty'),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='request_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanalytics.RequestEvent'),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanalytics.Visit'),
        ),
        migrations.AddField(
            model_name='pagepattern',
            name='page_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanalytics.PageType'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djanalytics.PageType'),
        ),
        migrations.AddField(
            model_name='domain',
            name='web_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djanalytics.WebProperty'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djanalytics.DeviceType'),
        ),
        migrations.AlterUniqueTogether(
            name='pagepattern',
            unique_together=set([('pattern', 'client')]),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('path', 'client')]),
        ),
        migrations.AlterIndexTogether(
            name='device',
            index_together=set([('screen_width', 'screen_height'), ('os', 'os_version'), ('browser', 'browser_version')]),
        ),
    ]
